### ISSUE TITLE
Importing SBML not working like it used to

### ISSUE THREAD

**Issue by lianamerk** [biocircuits/bioscrape#40] opened 2020-05-29 01:43 UTC
Hi bioscrape team,

I have an SBML model from class a few weeks ago that I used to be able to import fine. I updated bioscrape today to get inference, and now two methods of importing sbml files is failing. I've tried:

`bioscrape.sbmlutil.import_sbml(filename)` and `bioscrape.types.Model(sbml_filename = filename)`

Both are giving me: SBML File (filename) cannot be read without errors.

I can attach the file or test out more ways of importing if needed.

Thanks!!

**Comment by ayush9pandey** [comment] 2020-05-29 23:10
I have had this error earlier when the SBML filename was invalid or not present in the directory. Either that or the SBML file is empty somehow? Can you check if one of these is the case for you?

**Comment by lianamerk** [comment] 2020-05-30 00:14
The filename is valid and is present in the directory. I am able to read it in with other methods like "xmltodict" and "xml.etree.ElementTree"

**Comment by emlarsson** [comment] 2020-05-31 19:35
Hi,

When I try to save my Bioscrape model using:
"M.write_sbml_model("name.xml")"
I get an error saying one of the species is not found. Saving like this worked about a month ago when I saved an earlier version of my model. 

Thanks!

**Comment by WilliamIX** [comment] 2020-06-01 22:06
@ayush9pandey do you think this bioscrape issue is related to the problems you just fixed in biocrnpyler?

**Comment by ayush9pandey** [comment] 2020-06-01 22:09
I don't think so, I suspect this has something to do with latest commits to bioscrape? I haven't recreated the issue on my end yet.

**Comment by ayush9pandey** [comment] 2020-06-04 00:44
Thanks to Liana, we tracked down this issue . The problem is with species names that are not allowed in SBML (such as those having colons, semicolons etc.). This is activated when such a species is added in a reaction.

**Comment by ayush9pandey** [comment] 2020-06-16 04:59
Fixed with #50. 

It should throw an error now saying that SBML does not allow names with colons, etc. @lianamerk  whenever you have a chance can you check if that is the case?

**Closed by ayush9pandey** 2020-06-16 04:59 UTC
